apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: httpbinding
  namespace: default
spec:
  type: bindings.http
  version: v1
  metadata:
    - name: url
      value: http://localhost:7000/test